### ISSUE TITLE
Rename all mentions of the word "cart" to "carts"

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/carts#4]
We're using the wrong container name. Quite a big change.

**Comment by nustiueudinastea** [comment]
I see that the repo name is "carts", but there is no consistency among the services. Some use singular and some use a plural naming scheme. We could also just rename the repo to cart. It will probably generate less work.

Or is there some reasoning behind the inconsistency in the service names?

**Comment by nustiueudinastea** [comment]
This has been fixed.
